export {default as Hero} from './Hero'
export {default as FeaturedProducts} from './FeaturedProducts'
export {default as Testimonials} from './Testimonials'
export {default as Faq} from './Faq'
export {default as Accordion} from './Accordion'
